export const GET_MOVIES = 'GET_MOVIES';
export const ADD_MOVIE = 'ADD_MOVIE';
export const UPLOAD_MOVIES = 'UPLOAD_MOVIES';
export const DELETE_MOVIE = 'DELETE_MOVIE';
export const SEARCH_MOVIES_BY_TITLE = 'SEARCH_MOVIES_BY_TITLE';
export const SEARCH_MOVIES_BY_STAR = 'SEARCH_MOVIES_BY_STAR';
export const MOVIES_LOADING = 'ITEMS_MOVIES';
